version: "3.7"
services:
  proxy:
    image: nginx
    volumes:
      - ./index.html:/etc/nginx/html/index.html
      - ./nginx/nginx.conf/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - webapp
  webapp:
    image: tutum/hello-world
